wandb_version: 1

batch_size:
  desc: null
  value: 16
lr:
  desc: null
  value: 0.0001
epochs:
  desc: null
  value: 40
optimizer:
  desc: null
  value: SGD
_wandb:
  desc: null
  value:
    python_version: 3.12.1
    cli_version: 0.17.3
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1719596276
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      2:
      - 1
      - 5
      - 53
      - 55
      3:
      - 2
      - 7
      - 13
      - 16
      - 23
      4: 3.12.1
      5: 0.17.3
      8:
      - 1
      - 4
      - 5
      13: darwin-arm64
    m:
    - 1: batch_step
      6:
      - 3
    - 1: epoch
      6:
      - 3
    - 1: valid_loss
      5: 2
      6:
      - 1
      - 3
    - 1: train_loss
      5: 2
      6:
      - 1
      - 3
    - 1: runtime
      5: 2
      6:
      - 1
      - 3
    - 1: running_loss
      5: 1
      6:
      - 1
      - 3
